# Kubernetes Sidecar Example for SLZB-OTBR
# OTBR runs as a sidecar to Home Assistant, communicating via localhost

---
apiVersion: v1
kind: Namespace
metadata:
  name: home-assistant
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-data
  namespace: home-assistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: otbr-data
  namespace: home-assistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matter-server-data
  namespace: home-assistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: ha-credentials
  namespace: home-assistant
type: Opaque
stringData:
  # Home Assistant Long-Lived Access Token (for auto-extraction)
  token: "YOUR_HA_TOKEN_HERE"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: home-assistant
  namespace: home-assistant
  labels:
    app: home-assistant
spec:
  serviceName: home-assistant
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      # hostNetwork needed by Home Assistant for device discovery, mDNS, etc.
      # OTBR sidecar benefits from this but doesn't require it alone
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      
      volumes:
      - name: ha-data
        persistentVolumeClaim:
          claimName: home-assistant-data
      - name: otbr-data
        persistentVolumeClaim:
          claimName: otbr-data
      - name: matter-data
        persistentVolumeClaim:
          claimName: matter-server-data
      - name: dev-net-tun
        hostPath:
          path: /dev/net/tun
      
      containers:
      # ===================
      # Home Assistant
      # ===================
      - name: home-assistant
        image: homeassistant/home-assistant:2025.1
        ports:
        - containerPort: 8123
        volumeMounts:
        - name: ha-data
          mountPath: /config
        livenessProbe:
          httpGet:
            path: /
            port: 8123
          initialDelaySeconds: 60
          periodSeconds: 10
      
      # ===================
      # OTBR Sidecar
      # ===================
      # Connects to SLZB-MR1 over TCP and exposes REST API on localhost:8081
      - name: otbr
        image: ghcr.io/tiborv/slzb-otbr:latest
        securityContext:
          privileged: true
          capabilities:
            add: ["NET_ADMIN", "SYS_MODULE"]
        env:
        # Required: Your SLZB device IP
        - name: SLZB_HOST
          value: "192.168.1.235"
        - name: SLZB_PORT
          value: "6638"
        
        # Auto-extract Thread credentials from Home Assistant
        # HA is accessible at localhost:8123 since we're in the same pod
        - name: HA_URL
          value: "http://localhost:8123"
        - name: HA_TOKEN
          valueFrom:
            secretKeyRef:
              name: ha-credentials
              key: token
        - name: AUTO_EXTRACT
          value: "true"
        
        # OTBR settings
        - name: OT_THREAD_IF
          value: "wpan0"
        - name: OT_REST_LISTEN_PORT
          value: "8081"
        
        ports:
        - containerPort: 8081
          name: otbr-rest
        
        volumeMounts:
        - name: otbr-data
          mountPath: /data
        - name: dev-net-tun
          mountPath: /dev/net/tun
      
      # ===================
      # Matter Server Sidecar (Optional)
      # ===================
      - name: matter-server
        image: ghcr.io/home-assistant-libs/python-matter-server:stable
        args:
          - '--storage-path'
          - /data
          - '--paa-root-cert-dir'
          - /data/credentials
          - '--log-level'
          - info
        ports:
        - containerPort: 5580
          name: matter-ws
        volumeMounts:
        - name: matter-data
          mountPath: /data
---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  selector:
    app: home-assistant
  ports:
  - port: 80
    targetPort: 8123
    name: http
